export const Events = [
    {
        id: "1",
        title: "1 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "2 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "3 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "4 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "5 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "6 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "7 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Jugraj, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "8 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "9 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "10 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Jugraj, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "11 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "12 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "13 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "14 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "15 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "16 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "17 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "18 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "19 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "20 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "21 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "22 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "23 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "24 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "25 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "26 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "27 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "28 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "29 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },
    {
        id: "1",
        title: "30 IEEE SOCET SB INAUGURATION",
        date: "Dec 21, 2023",
        description: "Speaker : Dr. Manik Lal Das, Dr. Anu Gokhale",
    },

]